# Use an official Node.js runtime as a parent image
FROM node:20.10.0

# Set the working directory
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files
COPY package*.json ./

RUN ls -al

# Install dependencies
RUN npm install 

# Copy the rest of the application code
COPY . .

# Expose the port your app runs on
EXPOSE 5001

# Command to run your application
CMD ["node", "index.js"]


